on:
  push:
    branches: 
      - "dev*"

env:
  IMAGE_NAME: ${{ github.event.repository.name }}

name: 🔖 Create System Tags for Devs
jobs:
  build:
    name: 🔖 Bump tag
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create tag
      uses: kangketikonlen/base-tagging@v1.1
      env:
        REPO_NAME: ${{ github.event.repository.name }}
        REPO_OWNER: ${{ github.event.repository.owner.name }}
        REPO_TYPE: ${{ github.event.repository.owner.type }}
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}