on:
  push:
    branches: 
      - "devs"

env:
  IMAGE_NAME: ${{ github.event.repository.name }}

name: 🔖 Create System Tags
jobs:
  build:
    name: 🔖 Bump tag
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create tag
      uses: kangketikonlen/base-tagging@devs
      env:
        First_Name: Mona
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}